name = "d-lictitious-feast"
main = "src/index.ts"
compatibility_date = "2025-12-25"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "dlitticious"
database_id = "ce31d443-87e4-4c6a-9e64-df7b6030eb5b"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[vars]
AUTH_SECRET = "dlitticiousservesthebestlittichokhaaaintheworld"